[package]
name = "wow_vanilla_server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.2", features = ["full"]}
wow_login_messages = { git="https://github.com/gtker/wow_messages.git", rev = "9bfee5bad039675d524d9bb4a517b01cf5630dce", features = ["tokio"] }
wow_world_messages = { git="https://github.com/gtker/wow_messages.git", rev = "9bfee5bad039675d524d9bb4a517b01cf5630dce", features = ["tokio", "vanilla"] }
wow_common = { git="https://github.com/gtker/wow_messages.git", rev = "9bfee5bad039675d524d9bb4a517b01cf5630dce", features = ["vanilla"] }
#wow_login_messages = { path = "../../wow_messages/wow_login_messages", features = ["tokio"] }
#wow_world_messages = { path = "../../wow_messages/wow_world_messages", features = ["tokio", "vanilla"] }
#wow_common = { path = "../../wow_messages/wow_common/wow_common",features = ["vanilla"] }
wow_srp = "0.5.3"
