[package]
name = "wow_vanilla_server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.2", features = ["full"]}
wow_login_messages = { git="https://github.com/gtker/wow_messages.git", rev = "ee10ee8ae4382e313bf433f4a85e7a2848d2ff98", features = ["tokio"] }
wow_world_messages = { git="https://github.com/gtker/wow_messages.git", rev = "ee10ee8ae4382e313bf433f4a85e7a2848d2ff98", features = ["tokio", "vanilla"] }
wow_srp = "0.5.3"
wow_vanilla_common = { path = "../wow_vanilla_common" }
