[package]
name = "wow_vanilla_server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.2", features = ["full"]}
wow_login_messages = { git="https://github.com/gtker/wow_messages.git", rev = "e4bae24087284210ea1b23a4e6cd442841552e8e", features = ["tokio"] }
wow_world_messages = { git="https://github.com/gtker/wow_messages.git", rev = "e4bae24087284210ea1b23a4e6cd442841552e8e", features = ["tokio", "wrath"] }
wow_common = { git="https://github.com/gtker/wow_messages.git", rev = "e4bae24087284210ea1b23a4e6cd442841552e8e", features = ["wrath"] }
#wow_login_messages = { path = "../../wow_messages/wow_login_messages", features = ["tokio"] }
#wow_world_messages = { path = "../../wow_messages/wow_world_messages", features = ["tokio", "wrath"] }
#wow_common = { path = "../../wow_messages/wow_common/wow_common",features = ["wrath"] }
wow_srp = "0.5.3"
