[package]
name = "wow_vanilla_server"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.18.2", features = ["full"]}
wow_login_messages = { git="https://github.com/gtker/wow_messages.git", rev = "0a28ea67a44d93b383557d7b2d49f1181139f35b", features = ["tokio"] }
wow_world_messages = { git="https://github.com/gtker/wow_messages.git", rev = "0a28ea67a44d93b383557d7b2d49f1181139f35b", features = ["tokio", "vanilla"] }
wow_common = { git="https://github.com/gtker/wow_messages.git", rev = "0a28ea67a44d93b383557d7b2d49f1181139f35b", features = ["vanilla"] }
wow_srp = "0.5.3"
