use crate::world::database::WorldDatabase;
use crate::world::item::Item;
use wow_items::vanilla::lookup_item;
use wow_world_base::vanilla::{Guid, ItemSlot, StarterItem};
use wow_world_messages::vanilla::CharacterGear;

#[derive(Debug, Clone, Default)]
pub struct Inventory {
    pub head: Option<Item>,
    pub neck: Option<Item>,
    pub shoulders: Option<Item>,
    pub shirt: Option<Item>,
    pub chest: Option<Item>,
    pub waist: Option<Item>,
    pub legs: Option<Item>,
    pub boots: Option<Item>,
    pub wrist: Option<Item>,
    pub hands: Option<Item>,
    pub ring1: Option<Item>,
    pub ring2: Option<Item>,
    pub trinket1: Option<Item>,
    pub trinket2: Option<Item>,
    pub back: Option<Item>,
    pub main_hand: Option<Item>,
    pub off_hand: Option<Item>,
    pub ranged: Option<Item>,
    pub tabard: Option<Item>,
    pub bag1: Option<Item>,
    pub bag2: Option<Item>,
    pub bag3: Option<Item>,
    pub bag4: Option<Item>,
    pub inventory0: Option<Item>,
    pub inventory1: Option<Item>,
    pub inventory2: Option<Item>,
    pub inventory3: Option<Item>,
    pub inventory4: Option<Item>,
    pub inventory5: Option<Item>,
    pub inventory6: Option<Item>,
    pub inventory7: Option<Item>,
    pub inventory8: Option<Item>,
    pub inventory9: Option<Item>,
    pub inventory10: Option<Item>,
    pub inventory11: Option<Item>,
    pub inventory12: Option<Item>,
    pub inventory13: Option<Item>,
    pub inventory14: Option<Item>,
    pub inventory15: Option<Item>,
    pub bank1: Option<Item>,
    pub bank2: Option<Item>,
    pub bank3: Option<Item>,
    pub bank4: Option<Item>,
    pub bank5: Option<Item>,
    pub bank6: Option<Item>,
    pub bank7: Option<Item>,
    pub bank8: Option<Item>,
    pub bank9: Option<Item>,
    pub bank10: Option<Item>,
    pub bank11: Option<Item>,
    pub bank12: Option<Item>,
    pub bank13: Option<Item>,
    pub bank14: Option<Item>,
    pub bank15: Option<Item>,
    pub bank16: Option<Item>,
    pub bank17: Option<Item>,
    pub bank18: Option<Item>,
    pub bank19: Option<Item>,
    pub bank20: Option<Item>,
    pub bank21: Option<Item>,
    pub bank22: Option<Item>,
    pub bank23: Option<Item>,
    pub bank24: Option<Item>,
    pub bank_bag_slot1: Option<Item>,
    pub bank_bag_slot2: Option<Item>,
    pub bank_bag_slot3: Option<Item>,
    pub bank_bag_slot4: Option<Item>,
    pub bank_bag_slot5: Option<Item>,
    pub bank_bag_slot6: Option<Item>,
    pub vendor_buyback1: Option<Item>,
    pub vendor_buyback2: Option<Item>,
    pub vendor_buyback3: Option<Item>,
    pub vendor_buyback4: Option<Item>,
    pub vendor_buyback5: Option<Item>,
    pub vendor_buyback6: Option<Item>,
    pub vendor_buyback7: Option<Item>,
    pub vendor_buyback8: Option<Item>,
    pub vendor_buyback9: Option<Item>,
    pub vendor_buyback10: Option<Item>,
    pub vendor_buyback11: Option<Item>,
    pub vendor_buyback12: Option<Item>,
    pub key_ring1: Option<Item>,
    pub key_ring2: Option<Item>,
    pub key_ring3: Option<Item>,
    pub key_ring4: Option<Item>,
    pub key_ring5: Option<Item>,
    pub key_ring6: Option<Item>,
    pub key_ring7: Option<Item>,
    pub key_ring8: Option<Item>,
    pub key_ring9: Option<Item>,
    pub key_ring10: Option<Item>,
    pub key_ring11: Option<Item>,
    pub key_ring12: Option<Item>,
    pub key_ring13: Option<Item>,
    pub key_ring14: Option<Item>,
    pub key_ring15: Option<Item>,
    pub key_ring16: Option<Item>,
    pub key_ring17: Option<Item>,
    pub key_ring18: Option<Item>,
    pub key_ring19: Option<Item>,
    pub key_ring20: Option<Item>,
    pub key_ring21: Option<Item>,
    pub key_ring22: Option<Item>,
    pub key_ring23: Option<Item>,
    pub key_ring24: Option<Item>,
    pub key_ring25: Option<Item>,
    pub key_ring26: Option<Item>,
    pub key_ring27: Option<Item>,
    pub key_ring28: Option<Item>,
    pub key_ring29: Option<Item>,
    pub key_ring30: Option<Item>,
    pub key_ring31: Option<Item>,
    pub key_ring32: Option<Item>,
}

impl Inventory {
    pub fn new(starter_items: &[StarterItem], db: &mut WorldDatabase) -> Self {
        let mut s = Self::default();

        for item in starter_items {
            let i = Item::new(
                lookup_item(item.item).unwrap(),
                Guid::zero(),
                item.amount,
                db,
            );
            s.set(item.ty, i);
        }

        s
    }

    pub fn swap(&mut self, source: ItemSlot, destination: ItemSlot) {
        let source_temp = self.take(source);
        let dest_temp = self.take(destination);

        *self.get_mut(source) = dest_temp;
        *self.get_mut(destination) = source_temp;
    }

    pub fn insert_into_first_slot(&mut self, item: Item) -> Option<ItemSlot> {
        let slots = [
            (&mut self.inventory0, ItemSlot::Inventory0),
            (&mut self.inventory1, ItemSlot::Inventory1),
            (&mut self.inventory2, ItemSlot::Inventory2),
            (&mut self.inventory3, ItemSlot::Inventory3),
            (&mut self.inventory4, ItemSlot::Inventory4),
            (&mut self.inventory5, ItemSlot::Inventory5),
            (&mut self.inventory6, ItemSlot::Inventory6),
            (&mut self.inventory7, ItemSlot::Inventory7),
            (&mut self.inventory8, ItemSlot::Inventory8),
            (&mut self.inventory9, ItemSlot::Inventory9),
            (&mut self.inventory10, ItemSlot::Inventory10),
            (&mut self.inventory11, ItemSlot::Inventory11),
            (&mut self.inventory12, ItemSlot::Inventory12),
            (&mut self.inventory13, ItemSlot::Inventory13),
            (&mut self.inventory14, ItemSlot::Inventory14),
            (&mut self.inventory15, ItemSlot::Inventory15),
        ];

        for (i, slot) in slots {
            if i.is_none() {
                *i = Some(item);

                return Some(slot);
            }
        }

        None
    }

    pub fn all_slots(&self) -> [(Option<&Item>, ItemSlot); 113] {
        [
            (self.head.as_ref(), ItemSlot::Head),
            (self.neck.as_ref(), ItemSlot::Neck),
            (self.shoulders.as_ref(), ItemSlot::Shoulders),
            (self.shirt.as_ref(), ItemSlot::Shirt),
            (self.chest.as_ref(), ItemSlot::Chest),
            (self.waist.as_ref(), ItemSlot::Waist),
            (self.legs.as_ref(), ItemSlot::Legs),
            (self.boots.as_ref(), ItemSlot::Boots),
            (self.wrist.as_ref(), ItemSlot::Wrist),
            (self.hands.as_ref(), ItemSlot::Hands),
            (self.ring1.as_ref(), ItemSlot::Ring1),
            (self.ring2.as_ref(), ItemSlot::Ring2),
            (self.trinket1.as_ref(), ItemSlot::Trinket1),
            (self.trinket2.as_ref(), ItemSlot::Trinket2),
            (self.back.as_ref(), ItemSlot::Back),
            (self.main_hand.as_ref(), ItemSlot::MainHand),
            (self.off_hand.as_ref(), ItemSlot::OffHand),
            (self.ranged.as_ref(), ItemSlot::RangedOrRelic),
            (self.tabard.as_ref(), ItemSlot::Tabard),
            (self.bag1.as_ref(), ItemSlot::Bag1),
            (self.bag2.as_ref(), ItemSlot::Bag2),
            (self.bag3.as_ref(), ItemSlot::Bag3),
            (self.bag4.as_ref(), ItemSlot::Bag4),
            (self.inventory0.as_ref(), ItemSlot::Inventory0),
            (self.inventory1.as_ref(), ItemSlot::Inventory1),
            (self.inventory2.as_ref(), ItemSlot::Inventory2),
            (self.inventory3.as_ref(), ItemSlot::Inventory3),
            (self.inventory4.as_ref(), ItemSlot::Inventory4),
            (self.inventory5.as_ref(), ItemSlot::Inventory5),
            (self.inventory6.as_ref(), ItemSlot::Inventory6),
            (self.inventory7.as_ref(), ItemSlot::Inventory7),
            (self.inventory8.as_ref(), ItemSlot::Inventory8),
            (self.inventory9.as_ref(), ItemSlot::Inventory9),
            (self.inventory10.as_ref(), ItemSlot::Inventory10),
            (self.inventory11.as_ref(), ItemSlot::Inventory11),
            (self.inventory12.as_ref(), ItemSlot::Inventory12),
            (self.inventory13.as_ref(), ItemSlot::Inventory13),
            (self.inventory14.as_ref(), ItemSlot::Inventory14),
            (self.inventory15.as_ref(), ItemSlot::Inventory15),
            (self.bank1.as_ref(), ItemSlot::Bank1),
            (self.bank2.as_ref(), ItemSlot::Bank2),
            (self.bank3.as_ref(), ItemSlot::Bank3),
            (self.bank4.as_ref(), ItemSlot::Bank4),
            (self.bank5.as_ref(), ItemSlot::Bank5),
            (self.bank6.as_ref(), ItemSlot::Bank6),
            (self.bank7.as_ref(), ItemSlot::Bank7),
            (self.bank8.as_ref(), ItemSlot::Bank8),
            (self.bank9.as_ref(), ItemSlot::Bank9),
            (self.bank10.as_ref(), ItemSlot::Bank10),
            (self.bank11.as_ref(), ItemSlot::Bank11),
            (self.bank12.as_ref(), ItemSlot::Bank12),
            (self.bank13.as_ref(), ItemSlot::Bank13),
            (self.bank14.as_ref(), ItemSlot::Bank14),
            (self.bank15.as_ref(), ItemSlot::Bank15),
            (self.bank16.as_ref(), ItemSlot::Bank16),
            (self.bank17.as_ref(), ItemSlot::Bank17),
            (self.bank18.as_ref(), ItemSlot::Bank18),
            (self.bank19.as_ref(), ItemSlot::Bank19),
            (self.bank20.as_ref(), ItemSlot::Bank20),
            (self.bank21.as_ref(), ItemSlot::Bank21),
            (self.bank22.as_ref(), ItemSlot::Bank22),
            (self.bank23.as_ref(), ItemSlot::Bank23),
            (self.bank24.as_ref(), ItemSlot::Bank24),
            (self.bank_bag_slot1.as_ref(), ItemSlot::BankBagSlot1),
            (self.bank_bag_slot2.as_ref(), ItemSlot::BankBagSlot2),
            (self.bank_bag_slot3.as_ref(), ItemSlot::BankBagSlot3),
            (self.bank_bag_slot4.as_ref(), ItemSlot::BankBagSlot4),
            (self.bank_bag_slot5.as_ref(), ItemSlot::BankBagSlot5),
            (self.bank_bag_slot6.as_ref(), ItemSlot::BankBagSlot6),
            (self.vendor_buyback1.as_ref(), ItemSlot::VendorBuyback1),
            (self.vendor_buyback2.as_ref(), ItemSlot::VendorBuyback2),
            (self.vendor_buyback3.as_ref(), ItemSlot::VendorBuyback3),
            (self.vendor_buyback4.as_ref(), ItemSlot::VendorBuyback4),
            (self.vendor_buyback5.as_ref(), ItemSlot::VendorBuyback5),
            (self.vendor_buyback6.as_ref(), ItemSlot::VendorBuyback6),
            (self.vendor_buyback7.as_ref(), ItemSlot::VendorBuyback7),
            (self.vendor_buyback8.as_ref(), ItemSlot::VendorBuyback8),
            (self.vendor_buyback9.as_ref(), ItemSlot::VendorBuyback9),
            (self.vendor_buyback10.as_ref(), ItemSlot::VendorBuyback10),
            (self.vendor_buyback11.as_ref(), ItemSlot::VendorBuyback11),
            (self.vendor_buyback12.as_ref(), ItemSlot::VendorBuyback12),
            (self.key_ring1.as_ref(), ItemSlot::Keyring1),
            (self.key_ring2.as_ref(), ItemSlot::Keyring2),
            (self.key_ring3.as_ref(), ItemSlot::Keyring3),
            (self.key_ring4.as_ref(), ItemSlot::Keyring4),
            (self.key_ring5.as_ref(), ItemSlot::Keyring5),
            (self.key_ring6.as_ref(), ItemSlot::Keyring6),
            (self.key_ring7.as_ref(), ItemSlot::Keyring7),
            (self.key_ring8.as_ref(), ItemSlot::Keyring8),
            (self.key_ring9.as_ref(), ItemSlot::Keyring9),
            (self.key_ring10.as_ref(), ItemSlot::Keyring10),
            (self.key_ring11.as_ref(), ItemSlot::Keyring11),
            (self.key_ring12.as_ref(), ItemSlot::Keyring12),
            (self.key_ring13.as_ref(), ItemSlot::Keyring13),
            (self.key_ring14.as_ref(), ItemSlot::Keyring14),
            (self.key_ring15.as_ref(), ItemSlot::Keyring15),
            (self.key_ring16.as_ref(), ItemSlot::Keyring16),
            (self.key_ring17.as_ref(), ItemSlot::Keyring17),
            (self.key_ring18.as_ref(), ItemSlot::Keyring18),
            (self.key_ring19.as_ref(), ItemSlot::Keyring19),
            (self.key_ring20.as_ref(), ItemSlot::Keyring20),
            (self.key_ring21.as_ref(), ItemSlot::Keyring21),
            (self.key_ring22.as_ref(), ItemSlot::Keyring22),
            (self.key_ring23.as_ref(), ItemSlot::Keyring23),
            (self.key_ring24.as_ref(), ItemSlot::Keyring24),
            (self.key_ring25.as_ref(), ItemSlot::Keyring25),
            (self.key_ring26.as_ref(), ItemSlot::Keyring26),
            (self.key_ring27.as_ref(), ItemSlot::Keyring27),
            (self.key_ring28.as_ref(), ItemSlot::Keyring28),
            (self.key_ring29.as_ref(), ItemSlot::Keyring29),
            (self.key_ring30.as_ref(), ItemSlot::Keyring30),
            (self.key_ring31.as_ref(), ItemSlot::Keyring31),
            (self.key_ring32.as_ref(), ItemSlot::Keyring32),
        ]
    }

    pub fn equipment(&self) -> [(Option<&Item>, ItemSlot); 19] {
        [
            (self.head.as_ref(), ItemSlot::Head),
            (self.neck.as_ref(), ItemSlot::Neck),
            (self.shoulders.as_ref(), ItemSlot::Shoulders),
            (self.shirt.as_ref(), ItemSlot::Shirt),
            (self.chest.as_ref(), ItemSlot::Chest),
            (self.waist.as_ref(), ItemSlot::Waist),
            (self.legs.as_ref(), ItemSlot::Legs),
            (self.boots.as_ref(), ItemSlot::Boots),
            (self.wrist.as_ref(), ItemSlot::Wrist),
            (self.hands.as_ref(), ItemSlot::Hands),
            (self.ring1.as_ref(), ItemSlot::Ring1),
            (self.ring2.as_ref(), ItemSlot::Ring2),
            (self.trinket1.as_ref(), ItemSlot::Trinket1),
            (self.trinket2.as_ref(), ItemSlot::Trinket2),
            (self.back.as_ref(), ItemSlot::Back),
            (self.main_hand.as_ref(), ItemSlot::MainHand),
            (self.off_hand.as_ref(), ItemSlot::OffHand),
            (self.ranged.as_ref(), ItemSlot::RangedOrRelic),
            (self.tabard.as_ref(), ItemSlot::Tabard),
        ]
    }

    pub fn to_character_gear(&self) -> [CharacterGear; 19] {
        let mut gear = [CharacterGear::default(); 19];

        for (i, (item, _)) in self.equipment().iter().enumerate() {
            if let Some(item) = item {
                let g = CharacterGear {
                    equipment_display_id: item.item.display_id(),
                    inventory_type: item.item.inventory_type(),
                };
                gear[i] = g;
            } else {
                gear[i] = CharacterGear {
                    equipment_display_id: 0,
                    inventory_type: Default::default(),
                };
            }
        }

        gear
    }

    pub fn set(&mut self, item_slot: ItemSlot, item: Item) {
        *self.get_mut(item_slot) = Some(item);
    }

    pub fn clear(&mut self, item_slot: ItemSlot) {
        *self.get_mut(item_slot) = None;
    }

    pub fn take(&mut self, item_slot: ItemSlot) -> Option<Item> {
        self.get_mut(item_slot).take()
    }

    pub fn get(&self, item_slot: ItemSlot) -> Option<&Item> {
        self.inner_get(item_slot).as_ref()
    }

    fn inner_get(&self, item_slot: ItemSlot) -> &Option<Item> {
        match item_slot {
            ItemSlot::Head => &self.head,
            ItemSlot::Neck => &self.neck,
            ItemSlot::Shoulders => &self.shoulders,
            ItemSlot::Shirt => &self.shirt,
            ItemSlot::Chest => &self.chest,
            ItemSlot::Waist => &self.waist,
            ItemSlot::Legs => &self.legs,
            ItemSlot::Boots => &self.boots,
            ItemSlot::Wrist => &self.wrist,
            ItemSlot::Hands => &self.hands,
            ItemSlot::Ring1 => &self.ring1,
            ItemSlot::Ring2 => &self.ring2,
            ItemSlot::Trinket1 => &self.trinket1,
            ItemSlot::Trinket2 => &self.trinket2,
            ItemSlot::Back => &self.back,
            ItemSlot::MainHand => &self.main_hand,
            ItemSlot::OffHand => &self.off_hand,
            ItemSlot::RangedOrRelic => &self.ranged,
            ItemSlot::Tabard => &self.tabard,
            ItemSlot::Bag1 => &self.bag1,
            ItemSlot::Bag2 => &self.bag2,
            ItemSlot::Bag3 => &self.bag3,
            ItemSlot::Bag4 => &self.bag4,
            ItemSlot::Inventory0 => &self.inventory0,
            ItemSlot::Inventory1 => &self.inventory1,
            ItemSlot::Inventory2 => &self.inventory2,
            ItemSlot::Inventory3 => &self.inventory3,
            ItemSlot::Inventory4 => &self.inventory4,
            ItemSlot::Inventory5 => &self.inventory5,
            ItemSlot::Inventory6 => &self.inventory6,
            ItemSlot::Inventory7 => &self.inventory7,
            ItemSlot::Inventory8 => &self.inventory8,
            ItemSlot::Inventory9 => &self.inventory9,
            ItemSlot::Inventory10 => &self.inventory10,
            ItemSlot::Inventory11 => &self.inventory11,
            ItemSlot::Inventory12 => &self.inventory12,
            ItemSlot::Inventory13 => &self.inventory13,
            ItemSlot::Inventory14 => &self.inventory14,
            ItemSlot::Inventory15 => &self.inventory15,
            ItemSlot::Bank1 => &self.bank1,
            ItemSlot::Bank2 => &self.bank2,
            ItemSlot::Bank3 => &self.bank3,
            ItemSlot::Bank4 => &self.bank4,
            ItemSlot::Bank5 => &self.bank5,
            ItemSlot::Bank6 => &self.bank6,
            ItemSlot::Bank7 => &self.bank7,
            ItemSlot::Bank8 => &self.bank8,
            ItemSlot::Bank9 => &self.bank9,
            ItemSlot::Bank10 => &self.bank10,
            ItemSlot::Bank11 => &self.bank11,
            ItemSlot::Bank12 => &self.bank12,
            ItemSlot::Bank13 => &self.bank13,
            ItemSlot::Bank14 => &self.bank14,
            ItemSlot::Bank15 => &self.bank15,
            ItemSlot::Bank16 => &self.bank16,
            ItemSlot::Bank17 => &self.bank17,
            ItemSlot::Bank18 => &self.bank18,
            ItemSlot::Bank19 => &self.bank19,
            ItemSlot::Bank20 => &self.bank20,
            ItemSlot::Bank21 => &self.bank21,
            ItemSlot::Bank22 => &self.bank22,
            ItemSlot::Bank23 => &self.bank23,
            ItemSlot::Bank24 => &self.bank24,
            ItemSlot::BankBagSlot1 => &self.bank_bag_slot1,
            ItemSlot::BankBagSlot2 => &self.bank_bag_slot2,
            ItemSlot::BankBagSlot3 => &self.bank_bag_slot3,
            ItemSlot::BankBagSlot4 => &self.bank_bag_slot4,
            ItemSlot::BankBagSlot5 => &self.bank_bag_slot5,
            ItemSlot::BankBagSlot6 => &self.bank_bag_slot6,
            ItemSlot::VendorBuyback1 => &self.vendor_buyback1,
            ItemSlot::VendorBuyback2 => &self.vendor_buyback2,
            ItemSlot::VendorBuyback3 => &self.vendor_buyback3,
            ItemSlot::VendorBuyback4 => &self.vendor_buyback4,
            ItemSlot::VendorBuyback5 => &self.vendor_buyback5,
            ItemSlot::VendorBuyback6 => &self.vendor_buyback6,
            ItemSlot::VendorBuyback7 => &self.vendor_buyback7,
            ItemSlot::VendorBuyback8 => &self.vendor_buyback8,
            ItemSlot::VendorBuyback9 => &self.vendor_buyback9,
            ItemSlot::VendorBuyback10 => &self.vendor_buyback10,
            ItemSlot::VendorBuyback11 => &self.vendor_buyback11,
            ItemSlot::VendorBuyback12 => &self.vendor_buyback12,
            ItemSlot::Keyring1 => &self.key_ring1,
            ItemSlot::Keyring2 => &self.key_ring2,
            ItemSlot::Keyring3 => &self.key_ring3,
            ItemSlot::Keyring4 => &self.key_ring4,
            ItemSlot::Keyring5 => &self.key_ring5,
            ItemSlot::Keyring6 => &self.key_ring6,
            ItemSlot::Keyring7 => &self.key_ring7,
            ItemSlot::Keyring8 => &self.key_ring8,
            ItemSlot::Keyring9 => &self.key_ring9,
            ItemSlot::Keyring10 => &self.key_ring10,
            ItemSlot::Keyring11 => &self.key_ring11,
            ItemSlot::Keyring12 => &self.key_ring12,
            ItemSlot::Keyring13 => &self.key_ring13,
            ItemSlot::Keyring14 => &self.key_ring14,
            ItemSlot::Keyring15 => &self.key_ring15,
            ItemSlot::Keyring16 => &self.key_ring16,
            ItemSlot::Keyring17 => &self.key_ring17,
            ItemSlot::Keyring18 => &self.key_ring18,
            ItemSlot::Keyring19 => &self.key_ring19,
            ItemSlot::Keyring20 => &self.key_ring20,
            ItemSlot::Keyring21 => &self.key_ring21,
            ItemSlot::Keyring22 => &self.key_ring22,
            ItemSlot::Keyring23 => &self.key_ring23,
            ItemSlot::Keyring24 => &self.key_ring24,
            ItemSlot::Keyring25 => &self.key_ring25,
            ItemSlot::Keyring26 => &self.key_ring26,
            ItemSlot::Keyring27 => &self.key_ring27,
            ItemSlot::Keyring28 => &self.key_ring28,
            ItemSlot::Keyring29 => &self.key_ring29,
            ItemSlot::Keyring30 => &self.key_ring30,
            ItemSlot::Keyring31 => &self.key_ring31,
            ItemSlot::Keyring32 => &self.key_ring32,
        }
    }

    fn get_mut(&mut self, item_slot: ItemSlot) -> &mut Option<Item> {
        match item_slot {
            ItemSlot::Head => &mut self.head,
            ItemSlot::Neck => &mut self.neck,
            ItemSlot::Shoulders => &mut self.shoulders,
            ItemSlot::Shirt => &mut self.shirt,
            ItemSlot::Chest => &mut self.chest,
            ItemSlot::Waist => &mut self.waist,
            ItemSlot::Legs => &mut self.legs,
            ItemSlot::Boots => &mut self.boots,
            ItemSlot::Wrist => &mut self.wrist,
            ItemSlot::Hands => &mut self.hands,
            ItemSlot::Ring1 => &mut self.ring1,
            ItemSlot::Ring2 => &mut self.ring2,
            ItemSlot::Trinket1 => &mut self.trinket1,
            ItemSlot::Trinket2 => &mut self.trinket2,
            ItemSlot::Back => &mut self.back,
            ItemSlot::MainHand => &mut self.main_hand,
            ItemSlot::OffHand => &mut self.off_hand,
            ItemSlot::RangedOrRelic => &mut self.ranged,
            ItemSlot::Tabard => &mut self.tabard,
            ItemSlot::Bag1 => &mut self.bag1,
            ItemSlot::Bag2 => &mut self.bag2,
            ItemSlot::Bag3 => &mut self.bag3,
            ItemSlot::Bag4 => &mut self.bag4,
            ItemSlot::Inventory0 => &mut self.inventory0,
            ItemSlot::Inventory1 => &mut self.inventory1,
            ItemSlot::Inventory2 => &mut self.inventory2,
            ItemSlot::Inventory3 => &mut self.inventory3,
            ItemSlot::Inventory4 => &mut self.inventory4,
            ItemSlot::Inventory5 => &mut self.inventory5,
            ItemSlot::Inventory6 => &mut self.inventory6,
            ItemSlot::Inventory7 => &mut self.inventory7,
            ItemSlot::Inventory8 => &mut self.inventory8,
            ItemSlot::Inventory9 => &mut self.inventory9,
            ItemSlot::Inventory10 => &mut self.inventory10,
            ItemSlot::Inventory11 => &mut self.inventory11,
            ItemSlot::Inventory12 => &mut self.inventory12,
            ItemSlot::Inventory13 => &mut self.inventory13,
            ItemSlot::Inventory14 => &mut self.inventory14,
            ItemSlot::Inventory15 => &mut self.inventory15,
            ItemSlot::Bank1 => &mut self.bank1,
            ItemSlot::Bank2 => &mut self.bank2,
            ItemSlot::Bank3 => &mut self.bank3,
            ItemSlot::Bank4 => &mut self.bank4,
            ItemSlot::Bank5 => &mut self.bank5,
            ItemSlot::Bank6 => &mut self.bank6,
            ItemSlot::Bank7 => &mut self.bank7,
            ItemSlot::Bank8 => &mut self.bank8,
            ItemSlot::Bank9 => &mut self.bank9,
            ItemSlot::Bank10 => &mut self.bank10,
            ItemSlot::Bank11 => &mut self.bank11,
            ItemSlot::Bank12 => &mut self.bank12,
            ItemSlot::Bank13 => &mut self.bank13,
            ItemSlot::Bank14 => &mut self.bank14,
            ItemSlot::Bank15 => &mut self.bank15,
            ItemSlot::Bank16 => &mut self.bank16,
            ItemSlot::Bank17 => &mut self.bank17,
            ItemSlot::Bank18 => &mut self.bank18,
            ItemSlot::Bank19 => &mut self.bank19,
            ItemSlot::Bank20 => &mut self.bank20,
            ItemSlot::Bank21 => &mut self.bank21,
            ItemSlot::Bank22 => &mut self.bank22,
            ItemSlot::Bank23 => &mut self.bank23,
            ItemSlot::Bank24 => &mut self.bank24,
            ItemSlot::BankBagSlot1 => &mut self.bank_bag_slot1,
            ItemSlot::BankBagSlot2 => &mut self.bank_bag_slot2,
            ItemSlot::BankBagSlot3 => &mut self.bank_bag_slot3,
            ItemSlot::BankBagSlot4 => &mut self.bank_bag_slot4,
            ItemSlot::BankBagSlot5 => &mut self.bank_bag_slot5,
            ItemSlot::BankBagSlot6 => &mut self.bank_bag_slot6,
            ItemSlot::VendorBuyback1 => &mut self.vendor_buyback1,
            ItemSlot::VendorBuyback2 => &mut self.vendor_buyback2,
            ItemSlot::VendorBuyback3 => &mut self.vendor_buyback3,
            ItemSlot::VendorBuyback4 => &mut self.vendor_buyback4,
            ItemSlot::VendorBuyback5 => &mut self.vendor_buyback5,
            ItemSlot::VendorBuyback6 => &mut self.vendor_buyback6,
            ItemSlot::VendorBuyback7 => &mut self.vendor_buyback7,
            ItemSlot::VendorBuyback8 => &mut self.vendor_buyback8,
            ItemSlot::VendorBuyback9 => &mut self.vendor_buyback9,
            ItemSlot::VendorBuyback10 => &mut self.vendor_buyback10,
            ItemSlot::VendorBuyback11 => &mut self.vendor_buyback11,
            ItemSlot::VendorBuyback12 => &mut self.vendor_buyback12,
            ItemSlot::Keyring1 => &mut self.key_ring1,
            ItemSlot::Keyring2 => &mut self.key_ring2,
            ItemSlot::Keyring3 => &mut self.key_ring3,
            ItemSlot::Keyring4 => &mut self.key_ring4,
            ItemSlot::Keyring5 => &mut self.key_ring5,
            ItemSlot::Keyring6 => &mut self.key_ring6,
            ItemSlot::Keyring7 => &mut self.key_ring7,
            ItemSlot::Keyring8 => &mut self.key_ring8,
            ItemSlot::Keyring9 => &mut self.key_ring9,
            ItemSlot::Keyring10 => &mut self.key_ring10,
            ItemSlot::Keyring11 => &mut self.key_ring11,
            ItemSlot::Keyring12 => &mut self.key_ring12,
            ItemSlot::Keyring13 => &mut self.key_ring13,
            ItemSlot::Keyring14 => &mut self.key_ring14,
            ItemSlot::Keyring15 => &mut self.key_ring15,
            ItemSlot::Keyring16 => &mut self.key_ring16,
            ItemSlot::Keyring17 => &mut self.key_ring17,
            ItemSlot::Keyring18 => &mut self.key_ring18,
            ItemSlot::Keyring19 => &mut self.key_ring19,
            ItemSlot::Keyring20 => &mut self.key_ring20,
            ItemSlot::Keyring21 => &mut self.key_ring21,
            ItemSlot::Keyring22 => &mut self.key_ring22,
            ItemSlot::Keyring23 => &mut self.key_ring23,
            ItemSlot::Keyring24 => &mut self.key_ring24,
            ItemSlot::Keyring25 => &mut self.key_ring25,
            ItemSlot::Keyring26 => &mut self.key_ring26,
            ItemSlot::Keyring27 => &mut self.key_ring27,
            ItemSlot::Keyring28 => &mut self.key_ring28,
            ItemSlot::Keyring29 => &mut self.key_ring29,
            ItemSlot::Keyring30 => &mut self.key_ring30,
            ItemSlot::Keyring31 => &mut self.key_ring31,
            ItemSlot::Keyring32 => &mut self.key_ring32,
        }
    }
}
