use crate::world::database::WorldDatabase;
use crate::world::item::Item;
use wow_items::vanilla::lookup_item;
use wow_world_base::vanilla::{ItemSlot, StarterItem};
use wow_world_messages::vanilla::CharacterGear;

#[derive(Debug, Clone, Default)]
pub struct Inventory {
    pub head: Option<Item>,
    pub neck: Option<Item>,
    pub shoulders: Option<Item>,
    pub shirt: Option<Item>,
    pub chest: Option<Item>,
    pub waist: Option<Item>,
    pub legs: Option<Item>,
    pub boots: Option<Item>,
    pub wrist: Option<Item>,
    pub hands: Option<Item>,
    pub ring1: Option<Item>,
    pub ring2: Option<Item>,
    pub trinket1: Option<Item>,
    pub trinket2: Option<Item>,
    pub back: Option<Item>,
    pub main_hand: Option<Item>,
    pub off_hand: Option<Item>,
    pub ranged: Option<Item>,
    pub tabard: Option<Item>,
    pub bag1: Option<Item>,
    pub bag2: Option<Item>,
    pub bag3: Option<Item>,
    pub bag4: Option<Item>,
    pub inventory0: Option<Item>,
    pub inventory1: Option<Item>,
    pub inventory2: Option<Item>,
    pub inventory3: Option<Item>,
    pub inventory4: Option<Item>,
    pub inventory5: Option<Item>,
    pub inventory6: Option<Item>,
    pub inventory7: Option<Item>,
    pub inventory8: Option<Item>,
    pub inventory9: Option<Item>,
    pub inventory10: Option<Item>,
    pub inventory11: Option<Item>,
    pub inventory12: Option<Item>,
    pub inventory13: Option<Item>,
    pub inventory14: Option<Item>,
    pub inventory15: Option<Item>,
    pub bank1: Option<Item>,
    pub bank2: Option<Item>,
    pub bank3: Option<Item>,
    pub bank4: Option<Item>,
    pub bank5: Option<Item>,
    pub bank6: Option<Item>,
    pub bank7: Option<Item>,
    pub bank8: Option<Item>,
    pub bank9: Option<Item>,
    pub bank10: Option<Item>,
    pub bank11: Option<Item>,
    pub bank12: Option<Item>,
    pub bank13: Option<Item>,
    pub bank14: Option<Item>,
    pub bank15: Option<Item>,
    pub bank16: Option<Item>,
    pub bank17: Option<Item>,
    pub bank18: Option<Item>,
    pub bank19: Option<Item>,
    pub bank20: Option<Item>,
    pub bank21: Option<Item>,
    pub bank22: Option<Item>,
    pub bank23: Option<Item>,
    pub bank24: Option<Item>,
    pub bank_bag_slot1: Option<Item>,
    pub bank_bag_slot2: Option<Item>,
    pub bank_bag_slot3: Option<Item>,
    pub bank_bag_slot4: Option<Item>,
    pub bank_bag_slot5: Option<Item>,
    pub bank_bag_slot6: Option<Item>,
    pub vendor_buyback1: Option<Item>,
    pub vendor_buyback2: Option<Item>,
    pub vendor_buyback3: Option<Item>,
    pub vendor_buyback4: Option<Item>,
    pub vendor_buyback5: Option<Item>,
    pub vendor_buyback6: Option<Item>,
    pub vendor_buyback7: Option<Item>,
    pub vendor_buyback8: Option<Item>,
    pub vendor_buyback9: Option<Item>,
    pub vendor_buyback10: Option<Item>,
    pub vendor_buyback11: Option<Item>,
    pub vendor_buyback12: Option<Item>,
    pub key_ring1: Option<Item>,
    pub key_ring2: Option<Item>,
    pub key_ring3: Option<Item>,
    pub key_ring4: Option<Item>,
    pub key_ring5: Option<Item>,
    pub key_ring6: Option<Item>,
    pub key_ring7: Option<Item>,
    pub key_ring8: Option<Item>,
    pub key_ring9: Option<Item>,
    pub key_ring10: Option<Item>,
    pub key_ring11: Option<Item>,
    pub key_ring12: Option<Item>,
    pub key_ring13: Option<Item>,
    pub key_ring14: Option<Item>,
    pub key_ring15: Option<Item>,
    pub key_ring16: Option<Item>,
    pub key_ring17: Option<Item>,
    pub key_ring18: Option<Item>,
    pub key_ring19: Option<Item>,
    pub key_ring20: Option<Item>,
    pub key_ring21: Option<Item>,
    pub key_ring22: Option<Item>,
    pub key_ring23: Option<Item>,
    pub key_ring24: Option<Item>,
    pub key_ring25: Option<Item>,
    pub key_ring26: Option<Item>,
    pub key_ring27: Option<Item>,
    pub key_ring28: Option<Item>,
    pub key_ring29: Option<Item>,
    pub key_ring30: Option<Item>,
    pub key_ring31: Option<Item>,
    pub key_ring32: Option<Item>,
}

impl Inventory {
    pub fn new(starter_items: &[StarterItem], db: &mut WorldDatabase) -> Self {
        let mut s = Self::default();

        for item in starter_items {
            let i = Item::new(lookup_item(item.item).unwrap(), db);
            s.set(item.ty, i);
        }

        s
    }

    pub fn all_slots(&self) -> [(Option<&Item>, ItemSlot); 113] {
        [
            (self.head.as_ref(), ItemSlot::Head),
            (self.neck.as_ref(), ItemSlot::Neck),
            (self.shoulders.as_ref(), ItemSlot::Shoulders),
            (self.shirt.as_ref(), ItemSlot::Shirt),
            (self.chest.as_ref(), ItemSlot::Chest),
            (self.waist.as_ref(), ItemSlot::Waist),
            (self.legs.as_ref(), ItemSlot::Legs),
            (self.boots.as_ref(), ItemSlot::Boots),
            (self.wrist.as_ref(), ItemSlot::Wrist),
            (self.hands.as_ref(), ItemSlot::Hands),
            (self.ring1.as_ref(), ItemSlot::Ring1),
            (self.ring2.as_ref(), ItemSlot::Ring2),
            (self.trinket1.as_ref(), ItemSlot::Trinket1),
            (self.trinket2.as_ref(), ItemSlot::Trinket2),
            (self.back.as_ref(), ItemSlot::Back),
            (self.main_hand.as_ref(), ItemSlot::MainHand),
            (self.off_hand.as_ref(), ItemSlot::OffHand),
            (self.ranged.as_ref(), ItemSlot::RangedOrRelic),
            (self.tabard.as_ref(), ItemSlot::Tabard),
            (self.bag1.as_ref(), ItemSlot::Bag1),
            (self.bag2.as_ref(), ItemSlot::Bag2),
            (self.bag3.as_ref(), ItemSlot::Bag3),
            (self.bag4.as_ref(), ItemSlot::Bag4),
            (self.inventory0.as_ref(), ItemSlot::Inventory0),
            (self.inventory1.as_ref(), ItemSlot::Inventory1),
            (self.inventory2.as_ref(), ItemSlot::Inventory2),
            (self.inventory3.as_ref(), ItemSlot::Inventory3),
            (self.inventory4.as_ref(), ItemSlot::Inventory4),
            (self.inventory5.as_ref(), ItemSlot::Inventory5),
            (self.inventory6.as_ref(), ItemSlot::Inventory6),
            (self.inventory7.as_ref(), ItemSlot::Inventory7),
            (self.inventory8.as_ref(), ItemSlot::Inventory8),
            (self.inventory9.as_ref(), ItemSlot::Inventory9),
            (self.inventory10.as_ref(), ItemSlot::Inventory10),
            (self.inventory11.as_ref(), ItemSlot::Inventory11),
            (self.inventory12.as_ref(), ItemSlot::Inventory12),
            (self.inventory13.as_ref(), ItemSlot::Inventory13),
            (self.inventory14.as_ref(), ItemSlot::Inventory14),
            (self.inventory15.as_ref(), ItemSlot::Inventory15),
            (self.bank1.as_ref(), ItemSlot::Bank1),
            (self.bank2.as_ref(), ItemSlot::Bank2),
            (self.bank3.as_ref(), ItemSlot::Bank3),
            (self.bank4.as_ref(), ItemSlot::Bank4),
            (self.bank5.as_ref(), ItemSlot::Bank5),
            (self.bank6.as_ref(), ItemSlot::Bank6),
            (self.bank7.as_ref(), ItemSlot::Bank7),
            (self.bank8.as_ref(), ItemSlot::Bank8),
            (self.bank9.as_ref(), ItemSlot::Bank9),
            (self.bank10.as_ref(), ItemSlot::Bank10),
            (self.bank11.as_ref(), ItemSlot::Bank11),
            (self.bank12.as_ref(), ItemSlot::Bank12),
            (self.bank13.as_ref(), ItemSlot::Bank13),
            (self.bank14.as_ref(), ItemSlot::Bank14),
            (self.bank15.as_ref(), ItemSlot::Bank15),
            (self.bank16.as_ref(), ItemSlot::Bank16),
            (self.bank17.as_ref(), ItemSlot::Bank17),
            (self.bank18.as_ref(), ItemSlot::Bank18),
            (self.bank19.as_ref(), ItemSlot::Bank19),
            (self.bank20.as_ref(), ItemSlot::Bank20),
            (self.bank21.as_ref(), ItemSlot::Bank21),
            (self.bank22.as_ref(), ItemSlot::Bank22),
            (self.bank23.as_ref(), ItemSlot::Bank23),
            (self.bank24.as_ref(), ItemSlot::Bank24),
            (self.bank_bag_slot1.as_ref(), ItemSlot::BankBagSlot1),
            (self.bank_bag_slot2.as_ref(), ItemSlot::BankBagSlot2),
            (self.bank_bag_slot3.as_ref(), ItemSlot::BankBagSlot3),
            (self.bank_bag_slot4.as_ref(), ItemSlot::BankBagSlot4),
            (self.bank_bag_slot5.as_ref(), ItemSlot::BankBagSlot5),
            (self.bank_bag_slot6.as_ref(), ItemSlot::BankBagSlot6),
            (self.vendor_buyback1.as_ref(), ItemSlot::VendorBuyback1),
            (self.vendor_buyback2.as_ref(), ItemSlot::VendorBuyback2),
            (self.vendor_buyback3.as_ref(), ItemSlot::VendorBuyback3),
            (self.vendor_buyback4.as_ref(), ItemSlot::VendorBuyback4),
            (self.vendor_buyback5.as_ref(), ItemSlot::VendorBuyback5),
            (self.vendor_buyback6.as_ref(), ItemSlot::VendorBuyback6),
            (self.vendor_buyback7.as_ref(), ItemSlot::VendorBuyback7),
            (self.vendor_buyback8.as_ref(), ItemSlot::VendorBuyback8),
            (self.vendor_buyback9.as_ref(), ItemSlot::VendorBuyback9),
            (self.vendor_buyback10.as_ref(), ItemSlot::VendorBuyback10),
            (self.vendor_buyback11.as_ref(), ItemSlot::VendorBuyback11),
            (self.vendor_buyback12.as_ref(), ItemSlot::VendorBuyback12),
            (self.key_ring1.as_ref(), ItemSlot::Keyring1),
            (self.key_ring2.as_ref(), ItemSlot::Keyring2),
            (self.key_ring3.as_ref(), ItemSlot::Keyring3),
            (self.key_ring4.as_ref(), ItemSlot::Keyring4),
            (self.key_ring5.as_ref(), ItemSlot::Keyring5),
            (self.key_ring6.as_ref(), ItemSlot::Keyring6),
            (self.key_ring7.as_ref(), ItemSlot::Keyring7),
            (self.key_ring8.as_ref(), ItemSlot::Keyring8),
            (self.key_ring9.as_ref(), ItemSlot::Keyring9),
            (self.key_ring10.as_ref(), ItemSlot::Keyring10),
            (self.key_ring11.as_ref(), ItemSlot::Keyring11),
            (self.key_ring12.as_ref(), ItemSlot::Keyring12),
            (self.key_ring13.as_ref(), ItemSlot::Keyring13),
            (self.key_ring14.as_ref(), ItemSlot::Keyring14),
            (self.key_ring15.as_ref(), ItemSlot::Keyring15),
            (self.key_ring16.as_ref(), ItemSlot::Keyring16),
            (self.key_ring17.as_ref(), ItemSlot::Keyring17),
            (self.key_ring18.as_ref(), ItemSlot::Keyring18),
            (self.key_ring19.as_ref(), ItemSlot::Keyring19),
            (self.key_ring20.as_ref(), ItemSlot::Keyring20),
            (self.key_ring21.as_ref(), ItemSlot::Keyring21),
            (self.key_ring22.as_ref(), ItemSlot::Keyring22),
            (self.key_ring23.as_ref(), ItemSlot::Keyring23),
            (self.key_ring24.as_ref(), ItemSlot::Keyring24),
            (self.key_ring25.as_ref(), ItemSlot::Keyring25),
            (self.key_ring26.as_ref(), ItemSlot::Keyring26),
            (self.key_ring27.as_ref(), ItemSlot::Keyring27),
            (self.key_ring28.as_ref(), ItemSlot::Keyring28),
            (self.key_ring29.as_ref(), ItemSlot::Keyring29),
            (self.key_ring30.as_ref(), ItemSlot::Keyring30),
            (self.key_ring31.as_ref(), ItemSlot::Keyring31),
            (self.key_ring32.as_ref(), ItemSlot::Keyring32),
        ]
    }

    pub fn equipment(&self) -> [(Option<&Item>, ItemSlot); 19] {
        [
            (self.head.as_ref(), ItemSlot::Head),
            (self.neck.as_ref(), ItemSlot::Neck),
            (self.shoulders.as_ref(), ItemSlot::Shoulders),
            (self.shirt.as_ref(), ItemSlot::Shirt),
            (self.chest.as_ref(), ItemSlot::Chest),
            (self.waist.as_ref(), ItemSlot::Waist),
            (self.legs.as_ref(), ItemSlot::Legs),
            (self.boots.as_ref(), ItemSlot::Boots),
            (self.wrist.as_ref(), ItemSlot::Wrist),
            (self.hands.as_ref(), ItemSlot::Hands),
            (self.ring1.as_ref(), ItemSlot::Ring1),
            (self.ring2.as_ref(), ItemSlot::Ring2),
            (self.trinket1.as_ref(), ItemSlot::Trinket1),
            (self.trinket2.as_ref(), ItemSlot::Trinket2),
            (self.back.as_ref(), ItemSlot::Back),
            (self.main_hand.as_ref(), ItemSlot::MainHand),
            (self.off_hand.as_ref(), ItemSlot::OffHand),
            (self.ranged.as_ref(), ItemSlot::RangedOrRelic),
            (self.tabard.as_ref(), ItemSlot::Tabard),
        ]
    }

    pub fn to_character_gear(&self) -> [CharacterGear; 19] {
        let mut gear = [CharacterGear::default(); 19];

        for (i, (item, _)) in self.equipment().iter().enumerate() {
            if let Some(item) = item {
                let g = CharacterGear {
                    equipment_display_id: item.item.display_id(),
                    inventory_type: item.item.inventory_type(),
                };
                gear[i] = g;
            } else {
                gear[i] = CharacterGear {
                    equipment_display_id: 0,
                    inventory_type: Default::default(),
                };
            }
        }

        gear
    }

    pub fn get(&self, item_slot: ItemSlot) -> Option<&Item> {
        match item_slot {
            ItemSlot::Head => self.head.as_ref(),
            ItemSlot::Neck => self.neck.as_ref(),
            ItemSlot::Shoulders => self.shoulders.as_ref(),
            ItemSlot::Shirt => self.shirt.as_ref(),
            ItemSlot::Chest => self.chest.as_ref(),
            ItemSlot::Waist => self.waist.as_ref(),
            ItemSlot::Legs => self.legs.as_ref(),
            ItemSlot::Boots => self.boots.as_ref(),
            ItemSlot::Wrist => self.wrist.as_ref(),
            ItemSlot::Hands => self.hands.as_ref(),
            ItemSlot::Ring1 => self.ring1.as_ref(),
            ItemSlot::Ring2 => self.ring2.as_ref(),
            ItemSlot::Trinket1 => self.trinket1.as_ref(),
            ItemSlot::Trinket2 => self.trinket2.as_ref(),
            ItemSlot::Back => self.back.as_ref(),
            ItemSlot::MainHand => self.main_hand.as_ref(),
            ItemSlot::OffHand => self.off_hand.as_ref(),
            ItemSlot::RangedOrRelic => self.ranged.as_ref(),
            ItemSlot::Tabard => self.tabard.as_ref(),
            ItemSlot::Bag1 => self.bag1.as_ref(),
            ItemSlot::Bag2 => self.bag2.as_ref(),
            ItemSlot::Bag3 => self.bag3.as_ref(),
            ItemSlot::Bag4 => self.bag4.as_ref(),
            ItemSlot::Inventory0 => self.inventory0.as_ref(),
            ItemSlot::Inventory1 => self.inventory1.as_ref(),
            ItemSlot::Inventory2 => self.inventory2.as_ref(),
            ItemSlot::Inventory3 => self.inventory3.as_ref(),
            ItemSlot::Inventory4 => self.inventory4.as_ref(),
            ItemSlot::Inventory5 => self.inventory5.as_ref(),
            ItemSlot::Inventory6 => self.inventory6.as_ref(),
            ItemSlot::Inventory7 => self.inventory7.as_ref(),
            ItemSlot::Inventory8 => self.inventory8.as_ref(),
            ItemSlot::Inventory9 => self.inventory9.as_ref(),
            ItemSlot::Inventory10 => self.inventory10.as_ref(),
            ItemSlot::Inventory11 => self.inventory11.as_ref(),
            ItemSlot::Inventory12 => self.inventory12.as_ref(),
            ItemSlot::Inventory13 => self.inventory13.as_ref(),
            ItemSlot::Inventory14 => self.inventory14.as_ref(),
            ItemSlot::Inventory15 => self.inventory15.as_ref(),
            ItemSlot::Bank1 => self.bank1.as_ref(),
            ItemSlot::Bank2 => self.bank2.as_ref(),
            ItemSlot::Bank3 => self.bank3.as_ref(),
            ItemSlot::Bank4 => self.bank4.as_ref(),
            ItemSlot::Bank5 => self.bank5.as_ref(),
            ItemSlot::Bank6 => self.bank6.as_ref(),
            ItemSlot::Bank7 => self.bank7.as_ref(),
            ItemSlot::Bank8 => self.bank8.as_ref(),
            ItemSlot::Bank9 => self.bank9.as_ref(),
            ItemSlot::Bank10 => self.bank10.as_ref(),
            ItemSlot::Bank11 => self.bank11.as_ref(),
            ItemSlot::Bank12 => self.bank12.as_ref(),
            ItemSlot::Bank13 => self.bank13.as_ref(),
            ItemSlot::Bank14 => self.bank14.as_ref(),
            ItemSlot::Bank15 => self.bank15.as_ref(),
            ItemSlot::Bank16 => self.bank16.as_ref(),
            ItemSlot::Bank17 => self.bank17.as_ref(),
            ItemSlot::Bank18 => self.bank18.as_ref(),
            ItemSlot::Bank19 => self.bank19.as_ref(),
            ItemSlot::Bank20 => self.bank20.as_ref(),
            ItemSlot::Bank21 => self.bank21.as_ref(),
            ItemSlot::Bank22 => self.bank22.as_ref(),
            ItemSlot::Bank23 => self.bank23.as_ref(),
            ItemSlot::Bank24 => self.bank24.as_ref(),
            ItemSlot::BankBagSlot1 => self.bank_bag_slot1.as_ref(),
            ItemSlot::BankBagSlot2 => self.bank_bag_slot2.as_ref(),
            ItemSlot::BankBagSlot3 => self.bank_bag_slot3.as_ref(),
            ItemSlot::BankBagSlot4 => self.bank_bag_slot4.as_ref(),
            ItemSlot::BankBagSlot5 => self.bank_bag_slot5.as_ref(),
            ItemSlot::BankBagSlot6 => self.bank_bag_slot6.as_ref(),
            ItemSlot::VendorBuyback1 => self.vendor_buyback1.as_ref(),
            ItemSlot::VendorBuyback2 => self.vendor_buyback2.as_ref(),
            ItemSlot::VendorBuyback3 => self.vendor_buyback3.as_ref(),
            ItemSlot::VendorBuyback4 => self.vendor_buyback4.as_ref(),
            ItemSlot::VendorBuyback5 => self.vendor_buyback5.as_ref(),
            ItemSlot::VendorBuyback6 => self.vendor_buyback6.as_ref(),
            ItemSlot::VendorBuyback7 => self.vendor_buyback7.as_ref(),
            ItemSlot::VendorBuyback8 => self.vendor_buyback8.as_ref(),
            ItemSlot::VendorBuyback9 => self.vendor_buyback9.as_ref(),
            ItemSlot::VendorBuyback10 => self.vendor_buyback10.as_ref(),
            ItemSlot::VendorBuyback11 => self.vendor_buyback11.as_ref(),
            ItemSlot::VendorBuyback12 => self.vendor_buyback12.as_ref(),
            ItemSlot::Keyring1 => self.key_ring1.as_ref(),
            ItemSlot::Keyring2 => self.key_ring2.as_ref(),
            ItemSlot::Keyring3 => self.key_ring3.as_ref(),
            ItemSlot::Keyring4 => self.key_ring4.as_ref(),
            ItemSlot::Keyring5 => self.key_ring5.as_ref(),
            ItemSlot::Keyring6 => self.key_ring6.as_ref(),
            ItemSlot::Keyring7 => self.key_ring7.as_ref(),
            ItemSlot::Keyring8 => self.key_ring8.as_ref(),
            ItemSlot::Keyring9 => self.key_ring9.as_ref(),
            ItemSlot::Keyring10 => self.key_ring10.as_ref(),
            ItemSlot::Keyring11 => self.key_ring11.as_ref(),
            ItemSlot::Keyring12 => self.key_ring12.as_ref(),
            ItemSlot::Keyring13 => self.key_ring13.as_ref(),
            ItemSlot::Keyring14 => self.key_ring14.as_ref(),
            ItemSlot::Keyring15 => self.key_ring15.as_ref(),
            ItemSlot::Keyring16 => self.key_ring16.as_ref(),
            ItemSlot::Keyring17 => self.key_ring17.as_ref(),
            ItemSlot::Keyring18 => self.key_ring18.as_ref(),
            ItemSlot::Keyring19 => self.key_ring19.as_ref(),
            ItemSlot::Keyring20 => self.key_ring20.as_ref(),
            ItemSlot::Keyring21 => self.key_ring21.as_ref(),
            ItemSlot::Keyring22 => self.key_ring22.as_ref(),
            ItemSlot::Keyring23 => self.key_ring23.as_ref(),
            ItemSlot::Keyring24 => self.key_ring24.as_ref(),
            ItemSlot::Keyring25 => self.key_ring25.as_ref(),
            ItemSlot::Keyring26 => self.key_ring26.as_ref(),
            ItemSlot::Keyring27 => self.key_ring27.as_ref(),
            ItemSlot::Keyring28 => self.key_ring28.as_ref(),
            ItemSlot::Keyring29 => self.key_ring29.as_ref(),
            ItemSlot::Keyring30 => self.key_ring30.as_ref(),
            ItemSlot::Keyring31 => self.key_ring31.as_ref(),
            ItemSlot::Keyring32 => self.key_ring32.as_ref(),
        }
    }

    pub fn set(&mut self, item_slot: ItemSlot, item: Item) {
        match item_slot {
            ItemSlot::Head => self.head = Some(item),
            ItemSlot::Neck => self.neck = Some(item),
            ItemSlot::Shoulders => self.shoulders = Some(item),
            ItemSlot::Shirt => self.shirt = Some(item),
            ItemSlot::Chest => self.chest = Some(item),
            ItemSlot::Waist => self.waist = Some(item),
            ItemSlot::Legs => self.legs = Some(item),
            ItemSlot::Boots => self.boots = Some(item),
            ItemSlot::Wrist => self.wrist = Some(item),
            ItemSlot::Hands => self.hands = Some(item),
            ItemSlot::Ring1 => self.ring1 = Some(item),
            ItemSlot::Ring2 => self.ring2 = Some(item),
            ItemSlot::Trinket1 => self.trinket1 = Some(item),
            ItemSlot::Trinket2 => self.trinket2 = Some(item),
            ItemSlot::Back => self.back = Some(item),
            ItemSlot::MainHand => self.main_hand = Some(item),
            ItemSlot::OffHand => self.off_hand = Some(item),
            ItemSlot::RangedOrRelic => self.ranged = Some(item),
            ItemSlot::Tabard => self.tabard = Some(item),
            ItemSlot::Bag1 => self.bag1 = Some(item),
            ItemSlot::Bag2 => self.bag2 = Some(item),
            ItemSlot::Bag3 => self.bag3 = Some(item),
            ItemSlot::Bag4 => self.bag4 = Some(item),
            ItemSlot::Inventory0 => self.inventory0 = Some(item),
            ItemSlot::Inventory1 => self.inventory1 = Some(item),
            ItemSlot::Inventory2 => self.inventory2 = Some(item),
            ItemSlot::Inventory3 => self.inventory3 = Some(item),
            ItemSlot::Inventory4 => self.inventory4 = Some(item),
            ItemSlot::Inventory5 => self.inventory5 = Some(item),
            ItemSlot::Inventory6 => self.inventory6 = Some(item),
            ItemSlot::Inventory7 => self.inventory7 = Some(item),
            ItemSlot::Inventory8 => self.inventory8 = Some(item),
            ItemSlot::Inventory9 => self.inventory9 = Some(item),
            ItemSlot::Inventory10 => self.inventory10 = Some(item),
            ItemSlot::Inventory11 => self.inventory11 = Some(item),
            ItemSlot::Inventory12 => self.inventory12 = Some(item),
            ItemSlot::Inventory13 => self.inventory13 = Some(item),
            ItemSlot::Inventory14 => self.inventory14 = Some(item),
            ItemSlot::Inventory15 => self.inventory15 = Some(item),
            ItemSlot::Bank1 => self.bank1 = Some(item),
            ItemSlot::Bank2 => self.bank2 = Some(item),
            ItemSlot::Bank3 => self.bank3 = Some(item),
            ItemSlot::Bank4 => self.bank4 = Some(item),
            ItemSlot::Bank5 => self.bank5 = Some(item),
            ItemSlot::Bank6 => self.bank6 = Some(item),
            ItemSlot::Bank7 => self.bank7 = Some(item),
            ItemSlot::Bank8 => self.bank8 = Some(item),
            ItemSlot::Bank9 => self.bank9 = Some(item),
            ItemSlot::Bank10 => self.bank10 = Some(item),
            ItemSlot::Bank11 => self.bank11 = Some(item),
            ItemSlot::Bank12 => self.bank12 = Some(item),
            ItemSlot::Bank13 => self.bank13 = Some(item),
            ItemSlot::Bank14 => self.bank14 = Some(item),
            ItemSlot::Bank15 => self.bank15 = Some(item),
            ItemSlot::Bank16 => self.bank16 = Some(item),
            ItemSlot::Bank17 => self.bank17 = Some(item),
            ItemSlot::Bank18 => self.bank18 = Some(item),
            ItemSlot::Bank19 => self.bank19 = Some(item),
            ItemSlot::Bank20 => self.bank20 = Some(item),
            ItemSlot::Bank21 => self.bank21 = Some(item),
            ItemSlot::Bank22 => self.bank22 = Some(item),
            ItemSlot::Bank23 => self.bank23 = Some(item),
            ItemSlot::Bank24 => self.bank24 = Some(item),
            ItemSlot::BankBagSlot1 => self.bank_bag_slot1 = Some(item),
            ItemSlot::BankBagSlot2 => self.bank_bag_slot2 = Some(item),
            ItemSlot::BankBagSlot3 => self.bank_bag_slot3 = Some(item),
            ItemSlot::BankBagSlot4 => self.bank_bag_slot4 = Some(item),
            ItemSlot::BankBagSlot5 => self.bank_bag_slot5 = Some(item),
            ItemSlot::BankBagSlot6 => self.bank_bag_slot6 = Some(item),
            ItemSlot::VendorBuyback1 => self.vendor_buyback1 = Some(item),
            ItemSlot::VendorBuyback2 => self.vendor_buyback2 = Some(item),
            ItemSlot::VendorBuyback3 => self.vendor_buyback3 = Some(item),
            ItemSlot::VendorBuyback4 => self.vendor_buyback4 = Some(item),
            ItemSlot::VendorBuyback5 => self.vendor_buyback5 = Some(item),
            ItemSlot::VendorBuyback6 => self.vendor_buyback6 = Some(item),
            ItemSlot::VendorBuyback7 => self.vendor_buyback7 = Some(item),
            ItemSlot::VendorBuyback8 => self.vendor_buyback8 = Some(item),
            ItemSlot::VendorBuyback9 => self.vendor_buyback9 = Some(item),
            ItemSlot::VendorBuyback10 => self.vendor_buyback10 = Some(item),
            ItemSlot::VendorBuyback11 => self.vendor_buyback11 = Some(item),
            ItemSlot::VendorBuyback12 => self.vendor_buyback12 = Some(item),
            ItemSlot::Keyring1 => self.key_ring1 = Some(item),
            ItemSlot::Keyring2 => self.key_ring2 = Some(item),
            ItemSlot::Keyring3 => self.key_ring3 = Some(item),
            ItemSlot::Keyring4 => self.key_ring4 = Some(item),
            ItemSlot::Keyring5 => self.key_ring5 = Some(item),
            ItemSlot::Keyring6 => self.key_ring6 = Some(item),
            ItemSlot::Keyring7 => self.key_ring7 = Some(item),
            ItemSlot::Keyring8 => self.key_ring8 = Some(item),
            ItemSlot::Keyring9 => self.key_ring9 = Some(item),
            ItemSlot::Keyring10 => self.key_ring10 = Some(item),
            ItemSlot::Keyring11 => self.key_ring11 = Some(item),
            ItemSlot::Keyring12 => self.key_ring12 = Some(item),
            ItemSlot::Keyring13 => self.key_ring13 = Some(item),
            ItemSlot::Keyring14 => self.key_ring14 = Some(item),
            ItemSlot::Keyring15 => self.key_ring15 = Some(item),
            ItemSlot::Keyring16 => self.key_ring16 = Some(item),
            ItemSlot::Keyring17 => self.key_ring17 = Some(item),
            ItemSlot::Keyring18 => self.key_ring18 = Some(item),
            ItemSlot::Keyring19 => self.key_ring19 = Some(item),
            ItemSlot::Keyring20 => self.key_ring20 = Some(item),
            ItemSlot::Keyring21 => self.key_ring21 = Some(item),
            ItemSlot::Keyring22 => self.key_ring22 = Some(item),
            ItemSlot::Keyring23 => self.key_ring23 = Some(item),
            ItemSlot::Keyring24 => self.key_ring24 = Some(item),
            ItemSlot::Keyring25 => self.key_ring25 = Some(item),
            ItemSlot::Keyring26 => self.key_ring26 = Some(item),
            ItemSlot::Keyring27 => self.key_ring27 = Some(item),
            ItemSlot::Keyring28 => self.key_ring28 = Some(item),
            ItemSlot::Keyring29 => self.key_ring29 = Some(item),
            ItemSlot::Keyring30 => self.key_ring30 = Some(item),
            ItemSlot::Keyring31 => self.key_ring31 = Some(item),
            ItemSlot::Keyring32 => self.key_ring32 = Some(item),
        }
    }

    pub fn clear(&mut self, item_slot: ItemSlot) {
        match item_slot {
            ItemSlot::Head => self.head = None,
            ItemSlot::Neck => self.neck = None,
            ItemSlot::Shoulders => self.shoulders = None,
            ItemSlot::Shirt => self.shirt = None,
            ItemSlot::Chest => self.chest = None,
            ItemSlot::Waist => self.waist = None,
            ItemSlot::Legs => self.legs = None,
            ItemSlot::Boots => self.boots = None,
            ItemSlot::Wrist => self.wrist = None,
            ItemSlot::Hands => self.hands = None,
            ItemSlot::Ring1 => self.ring1 = None,
            ItemSlot::Ring2 => self.ring2 = None,
            ItemSlot::Trinket1 => self.trinket1 = None,
            ItemSlot::Trinket2 => self.trinket2 = None,
            ItemSlot::Back => self.back = None,
            ItemSlot::MainHand => self.main_hand = None,
            ItemSlot::OffHand => self.off_hand = None,
            ItemSlot::RangedOrRelic => self.ranged = None,
            ItemSlot::Tabard => self.tabard = None,
            ItemSlot::Bag1 => self.bag1 = None,
            ItemSlot::Bag2 => self.bag2 = None,
            ItemSlot::Bag3 => self.bag3 = None,
            ItemSlot::Bag4 => self.bag4 = None,
            ItemSlot::Inventory0 => self.inventory0 = None,
            ItemSlot::Inventory1 => self.inventory1 = None,
            ItemSlot::Inventory2 => self.inventory2 = None,
            ItemSlot::Inventory3 => self.inventory3 = None,
            ItemSlot::Inventory4 => self.inventory4 = None,
            ItemSlot::Inventory5 => self.inventory5 = None,
            ItemSlot::Inventory6 => self.inventory6 = None,
            ItemSlot::Inventory7 => self.inventory7 = None,
            ItemSlot::Inventory8 => self.inventory8 = None,
            ItemSlot::Inventory9 => self.inventory9 = None,
            ItemSlot::Inventory10 => self.inventory10 = None,
            ItemSlot::Inventory11 => self.inventory11 = None,
            ItemSlot::Inventory12 => self.inventory12 = None,
            ItemSlot::Inventory13 => self.inventory13 = None,
            ItemSlot::Inventory14 => self.inventory14 = None,
            ItemSlot::Inventory15 => self.inventory15 = None,
            ItemSlot::Bank1 => self.bank1 = None,
            ItemSlot::Bank2 => self.bank2 = None,
            ItemSlot::Bank3 => self.bank3 = None,
            ItemSlot::Bank4 => self.bank4 = None,
            ItemSlot::Bank5 => self.bank5 = None,
            ItemSlot::Bank6 => self.bank6 = None,
            ItemSlot::Bank7 => self.bank7 = None,
            ItemSlot::Bank8 => self.bank8 = None,
            ItemSlot::Bank9 => self.bank9 = None,
            ItemSlot::Bank10 => self.bank10 = None,
            ItemSlot::Bank11 => self.bank11 = None,
            ItemSlot::Bank12 => self.bank12 = None,
            ItemSlot::Bank13 => self.bank13 = None,
            ItemSlot::Bank14 => self.bank14 = None,
            ItemSlot::Bank15 => self.bank15 = None,
            ItemSlot::Bank16 => self.bank16 = None,
            ItemSlot::Bank17 => self.bank17 = None,
            ItemSlot::Bank18 => self.bank18 = None,
            ItemSlot::Bank19 => self.bank19 = None,
            ItemSlot::Bank20 => self.bank20 = None,
            ItemSlot::Bank21 => self.bank21 = None,
            ItemSlot::Bank22 => self.bank22 = None,
            ItemSlot::Bank23 => self.bank23 = None,
            ItemSlot::Bank24 => self.bank24 = None,
            ItemSlot::BankBagSlot1 => self.bank_bag_slot1 = None,
            ItemSlot::BankBagSlot2 => self.bank_bag_slot2 = None,
            ItemSlot::BankBagSlot3 => self.bank_bag_slot3 = None,
            ItemSlot::BankBagSlot4 => self.bank_bag_slot4 = None,
            ItemSlot::BankBagSlot5 => self.bank_bag_slot5 = None,
            ItemSlot::BankBagSlot6 => self.bank_bag_slot6 = None,
            ItemSlot::VendorBuyback1 => self.vendor_buyback1 = None,
            ItemSlot::VendorBuyback2 => self.vendor_buyback2 = None,
            ItemSlot::VendorBuyback3 => self.vendor_buyback3 = None,
            ItemSlot::VendorBuyback4 => self.vendor_buyback4 = None,
            ItemSlot::VendorBuyback5 => self.vendor_buyback5 = None,
            ItemSlot::VendorBuyback6 => self.vendor_buyback6 = None,
            ItemSlot::VendorBuyback7 => self.vendor_buyback7 = None,
            ItemSlot::VendorBuyback8 => self.vendor_buyback8 = None,
            ItemSlot::VendorBuyback9 => self.vendor_buyback9 = None,
            ItemSlot::VendorBuyback10 => self.vendor_buyback10 = None,
            ItemSlot::VendorBuyback11 => self.vendor_buyback11 = None,
            ItemSlot::VendorBuyback12 => self.vendor_buyback12 = None,
            ItemSlot::Keyring1 => self.key_ring1 = None,
            ItemSlot::Keyring2 => self.key_ring2 = None,
            ItemSlot::Keyring3 => self.key_ring3 = None,
            ItemSlot::Keyring4 => self.key_ring4 = None,
            ItemSlot::Keyring5 => self.key_ring5 = None,
            ItemSlot::Keyring6 => self.key_ring6 = None,
            ItemSlot::Keyring7 => self.key_ring7 = None,
            ItemSlot::Keyring8 => self.key_ring8 = None,
            ItemSlot::Keyring9 => self.key_ring9 = None,
            ItemSlot::Keyring10 => self.key_ring10 = None,
            ItemSlot::Keyring11 => self.key_ring11 = None,
            ItemSlot::Keyring12 => self.key_ring12 = None,
            ItemSlot::Keyring13 => self.key_ring13 = None,
            ItemSlot::Keyring14 => self.key_ring14 = None,
            ItemSlot::Keyring15 => self.key_ring15 = None,
            ItemSlot::Keyring16 => self.key_ring16 = None,
            ItemSlot::Keyring17 => self.key_ring17 = None,
            ItemSlot::Keyring18 => self.key_ring18 = None,
            ItemSlot::Keyring19 => self.key_ring19 = None,
            ItemSlot::Keyring20 => self.key_ring20 = None,
            ItemSlot::Keyring21 => self.key_ring21 = None,
            ItemSlot::Keyring22 => self.key_ring22 = None,
            ItemSlot::Keyring23 => self.key_ring23 = None,
            ItemSlot::Keyring24 => self.key_ring24 = None,
            ItemSlot::Keyring25 => self.key_ring25 = None,
            ItemSlot::Keyring26 => self.key_ring26 = None,
            ItemSlot::Keyring27 => self.key_ring27 = None,
            ItemSlot::Keyring28 => self.key_ring28 = None,
            ItemSlot::Keyring29 => self.key_ring29 = None,
            ItemSlot::Keyring30 => self.key_ring30 = None,
            ItemSlot::Keyring31 => self.key_ring31 = None,
            ItemSlot::Keyring32 => self.key_ring32 = None,
        }
    }

    pub fn take(&mut self, item_slot: ItemSlot) -> Option<Item> {
        match item_slot {
            ItemSlot::Head => self.head.take(),
            ItemSlot::Neck => self.neck.take(),
            ItemSlot::Shoulders => self.shoulders.take(),
            ItemSlot::Shirt => self.shirt.take(),
            ItemSlot::Chest => self.chest.take(),
            ItemSlot::Waist => self.waist.take(),
            ItemSlot::Legs => self.legs.take(),
            ItemSlot::Boots => self.boots.take(),
            ItemSlot::Wrist => self.wrist.take(),
            ItemSlot::Hands => self.hands.take(),
            ItemSlot::Ring1 => self.ring1.take(),
            ItemSlot::Ring2 => self.ring2.take(),
            ItemSlot::Trinket1 => self.trinket1.take(),
            ItemSlot::Trinket2 => self.trinket2.take(),
            ItemSlot::Back => self.back.take(),
            ItemSlot::MainHand => self.main_hand.take(),
            ItemSlot::OffHand => self.off_hand.take(),
            ItemSlot::RangedOrRelic => self.ranged.take(),
            ItemSlot::Tabard => self.tabard.take(),
            ItemSlot::Bag1 => self.bag1.take(),
            ItemSlot::Bag2 => self.bag2.take(),
            ItemSlot::Bag3 => self.bag3.take(),
            ItemSlot::Bag4 => self.bag4.take(),
            ItemSlot::Inventory0 => self.inventory0.take(),
            ItemSlot::Inventory1 => self.inventory1.take(),
            ItemSlot::Inventory2 => self.inventory2.take(),
            ItemSlot::Inventory3 => self.inventory3.take(),
            ItemSlot::Inventory4 => self.inventory4.take(),
            ItemSlot::Inventory5 => self.inventory5.take(),
            ItemSlot::Inventory6 => self.inventory6.take(),
            ItemSlot::Inventory7 => self.inventory7.take(),
            ItemSlot::Inventory8 => self.inventory8.take(),
            ItemSlot::Inventory9 => self.inventory9.take(),
            ItemSlot::Inventory10 => self.inventory10.take(),
            ItemSlot::Inventory11 => self.inventory11.take(),
            ItemSlot::Inventory12 => self.inventory12.take(),
            ItemSlot::Inventory13 => self.inventory13.take(),
            ItemSlot::Inventory14 => self.inventory14.take(),
            ItemSlot::Inventory15 => self.inventory15.take(),
            ItemSlot::Bank1 => self.bank1.take(),
            ItemSlot::Bank2 => self.bank2.take(),
            ItemSlot::Bank3 => self.bank3.take(),
            ItemSlot::Bank4 => self.bank4.take(),
            ItemSlot::Bank5 => self.bank5.take(),
            ItemSlot::Bank6 => self.bank6.take(),
            ItemSlot::Bank7 => self.bank7.take(),
            ItemSlot::Bank8 => self.bank8.take(),
            ItemSlot::Bank9 => self.bank9.take(),
            ItemSlot::Bank10 => self.bank10.take(),
            ItemSlot::Bank11 => self.bank11.take(),
            ItemSlot::Bank12 => self.bank12.take(),
            ItemSlot::Bank13 => self.bank13.take(),
            ItemSlot::Bank14 => self.bank14.take(),
            ItemSlot::Bank15 => self.bank15.take(),
            ItemSlot::Bank16 => self.bank16.take(),
            ItemSlot::Bank17 => self.bank17.take(),
            ItemSlot::Bank18 => self.bank18.take(),
            ItemSlot::Bank19 => self.bank19.take(),
            ItemSlot::Bank20 => self.bank20.take(),
            ItemSlot::Bank21 => self.bank21.take(),
            ItemSlot::Bank22 => self.bank22.take(),
            ItemSlot::Bank23 => self.bank23.take(),
            ItemSlot::Bank24 => self.bank24.take(),
            ItemSlot::BankBagSlot1 => self.bank_bag_slot1.take(),
            ItemSlot::BankBagSlot2 => self.bank_bag_slot2.take(),
            ItemSlot::BankBagSlot3 => self.bank_bag_slot3.take(),
            ItemSlot::BankBagSlot4 => self.bank_bag_slot4.take(),
            ItemSlot::BankBagSlot5 => self.bank_bag_slot5.take(),
            ItemSlot::BankBagSlot6 => self.bank_bag_slot6.take(),
            ItemSlot::VendorBuyback1 => self.vendor_buyback1.take(),
            ItemSlot::VendorBuyback2 => self.vendor_buyback2.take(),
            ItemSlot::VendorBuyback3 => self.vendor_buyback3.take(),
            ItemSlot::VendorBuyback4 => self.vendor_buyback4.take(),
            ItemSlot::VendorBuyback5 => self.vendor_buyback5.take(),
            ItemSlot::VendorBuyback6 => self.vendor_buyback6.take(),
            ItemSlot::VendorBuyback7 => self.vendor_buyback7.take(),
            ItemSlot::VendorBuyback8 => self.vendor_buyback8.take(),
            ItemSlot::VendorBuyback9 => self.vendor_buyback9.take(),
            ItemSlot::VendorBuyback10 => self.vendor_buyback10.take(),
            ItemSlot::VendorBuyback11 => self.vendor_buyback11.take(),
            ItemSlot::VendorBuyback12 => self.vendor_buyback12.take(),
            ItemSlot::Keyring1 => self.key_ring1.take(),
            ItemSlot::Keyring2 => self.key_ring2.take(),
            ItemSlot::Keyring3 => self.key_ring3.take(),
            ItemSlot::Keyring4 => self.key_ring4.take(),
            ItemSlot::Keyring5 => self.key_ring5.take(),
            ItemSlot::Keyring6 => self.key_ring6.take(),
            ItemSlot::Keyring7 => self.key_ring7.take(),
            ItemSlot::Keyring8 => self.key_ring8.take(),
            ItemSlot::Keyring9 => self.key_ring9.take(),
            ItemSlot::Keyring10 => self.key_ring10.take(),
            ItemSlot::Keyring11 => self.key_ring11.take(),
            ItemSlot::Keyring12 => self.key_ring12.take(),
            ItemSlot::Keyring13 => self.key_ring13.take(),
            ItemSlot::Keyring14 => self.key_ring14.take(),
            ItemSlot::Keyring15 => self.key_ring15.take(),
            ItemSlot::Keyring16 => self.key_ring16.take(),
            ItemSlot::Keyring17 => self.key_ring17.take(),
            ItemSlot::Keyring18 => self.key_ring18.take(),
            ItemSlot::Keyring19 => self.key_ring19.take(),
            ItemSlot::Keyring20 => self.key_ring20.take(),
            ItemSlot::Keyring21 => self.key_ring21.take(),
            ItemSlot::Keyring22 => self.key_ring22.take(),
            ItemSlot::Keyring23 => self.key_ring23.take(),
            ItemSlot::Keyring24 => self.key_ring24.take(),
            ItemSlot::Keyring25 => self.key_ring25.take(),
            ItemSlot::Keyring26 => self.key_ring26.take(),
            ItemSlot::Keyring27 => self.key_ring27.take(),
            ItemSlot::Keyring28 => self.key_ring28.take(),
            ItemSlot::Keyring29 => self.key_ring29.take(),
            ItemSlot::Keyring30 => self.key_ring30.take(),
            ItemSlot::Keyring31 => self.key_ring31.take(),
            ItemSlot::Keyring32 => self.key_ring32.take(),
        }
    }
}
