[package]
name = "wow_vanilla_common"
version = "0.1.0"
edition = "2021"

[dependencies]
wow_world_base = { git="https://github.com/gtker/wow_messages.git", rev = "5e454e7e0a68b54d5c88253c357674d8fb899c5b" }
